package com.commuteeazy.commuteeazy.Domain;
// Generated Feb 19, 2022 9:01:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MatatuOperator generated by hbm2java
 */
@Entity
@Table(name="matatu_operator"
    ,schema="public"
)
public class MatatuOperator  implements java.io.Serializable {


     private int id;
     private String operatorName;
     private String emailAddress;
     private String phone;
     private Set<Route> routes = new HashSet<Route>(0);
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public MatatuOperator() {
    }

	
    public MatatuOperator(int id) {
        this.id = id;
    }
    public MatatuOperator(int id, String operatorName, String emailAddress, String phone, Set<Route> routes, Set<Vehicle> vehicles) {
       this.id = id;
       this.operatorName = operatorName;
       this.emailAddress = emailAddress;
       this.phone = phone;
       this.routes = routes;
       this.vehicles = vehicles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="operator_name", length=100)
    public String getOperatorName() {
        return this.operatorName;
    }
    
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    
    @Column(name="email_address", length=100)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="phone", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matatuOperator")
    public Set<Route> getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Set<Route> routes) {
        this.routes = routes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matatuOperator")
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }




}


