package com.commuteeazy.commuteeazy.Domain;
// Generated Feb 18, 2022 1:14:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,schema="public"
)
public class Roles  implements java.io.Serializable {


     private int id;
     private String rolename;

    public Roles() {
    }

	
    public Roles(int id) {
        this.id = id;
    }
    public Roles(int id, String rolename) {
       this.id = id;
       this.rolename = rolename;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="rolename", length=50)
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }




}


