package com.commuteeazy.commuteeazy.Domain;
// Generated Feb 19, 2022 9:01:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name="route"
    ,schema="public"
)
public class Route  implements java.io.Serializable {


     private int id;
     private MatatuOperator matatuOperator;
     private String routename;
     private String description;
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);
     private Set<Place> places = new HashSet<Place>(0);

    public Route() {
    }

	
    public Route(int id) {
        this.id = id;
    }
    public Route(int id, MatatuOperator matatuOperator, String routename, String description, Set<Vehicle> vehicles, Set<Place> places) {
       this.id = id;
       this.matatuOperator = matatuOperator;
       this.routename = routename;
       this.description = description;
       this.vehicles = vehicles;
       this.places = places;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="matatu_operator")
    public MatatuOperator getMatatuOperator() {
        return this.matatuOperator;
    }
    
    public void setMatatuOperator(MatatuOperator matatuOperator) {
        this.matatuOperator = matatuOperator;
    }

    
    @Column(name="routename", length=50)
    public String getRoutename() {
        return this.routename;
    }
    
    public void setRoutename(String routename) {
        this.routename = routename;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<Place> getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Set<Place> places) {
        this.places = places;
    }




}


