package com.commuteeazy.commuteeazy.Domain;
// Generated Oct 13, 2021 10:14:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name="vehicle"
    ,schema="public"
)
public class Vehicle  implements java.io.Serializable {


     private int id;
     private MatatuOperator matatuOperator;
     private Route route;
     private String regno;
     private String make;
     private String model;

    public Vehicle() {
    }

	
    public Vehicle(int id) {
        this.id = id;
    }
    public Vehicle(int id, MatatuOperator matatuOperator, Route route, String regno, String make, String model) {
       this.id = id;
       this.matatuOperator = matatuOperator;
       this.route = route;
       this.regno = regno;
       this.make = make;
       this.model = model;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="matatu_operator")
    public MatatuOperator getMatatuOperator() {
        return this.matatuOperator;
    }
    
    public void setMatatuOperator(MatatuOperator matatuOperator) {
        this.matatuOperator = matatuOperator;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="route")
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    
    @Column(name="regno", length=100)
    public String getRegno() {
        return this.regno;
    }
    
    public void setRegno(String regno) {
        this.regno = regno;
    }

    
    @Column(name="make", length=100)
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }

    
    @Column(name="model", length=100)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }




}


